# Base image
FROM node:20

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY package*.json ./
RUN npm install

# Add app
COPY . ./

# Start app
CMD ["npm", "run", "dev"]