// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for about documents
 */
interface AboutDocumentData {
  /**
   * title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * description field in *about*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *about*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *about*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *about*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type CollapsibleCollectionDocumentDataSlicesSlice = LinkWithImageSlice;

/**
 * Content for collapsible collection documents
 */
interface CollapsibleCollectionDocumentData {
  /**
   * Slice Zone field in *collapsible collection*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: collapsible_collection.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CollapsibleCollectionDocumentDataSlicesSlice>;
}

/**
 * collapsible collection document from Prismic
 *
 * - **API ID**: `collapsible_collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollapsibleCollectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CollapsibleCollectionDocumentData>,
    "collapsible_collection",
    Lang
  >;

type EpisodeDocumentDataSlicesSlice = never;

/**
 * Content for episode documents
 */
interface EpisodeDocumentData {
  /**
   * image field in *episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * release date field in *episode*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.release_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * music_links field in *episode*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.music_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  music_links: prismic.LinkField;

  /**
   * Slice Zone field in *episode*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EpisodeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: episode.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: episode.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * episode document from Prismic
 *
 * - **API ID**: `episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EpisodeDocumentData>,
    "episode",
    Lang
  >;

type EpisodesDocumentDataSlicesSlice = ChapterSlice;

/**
 * Content for episodes documents
 */
interface EpisodesDocumentData {
  /**
   * title field in *episodes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *episodes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * description field in *episodes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *episodes*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EpisodesDocumentDataSlicesSlice>
  /**
   * Meta Description field in *episodes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: episodes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *episodes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *episodes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: episodes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * episodes document from Prismic
 *
 * - **API ID**: `episodes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EpisodesDocumentData>,
    "episodes",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type NavDocumentDataSlicesSlice = NavLinksSlice;

/**
 * Content for nav documents
 */
interface NavDocumentData {
  /**
   * logo field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *nav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavDocumentDataSlicesSlice>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

/**
 * Item in *theme → default*
 */
export interface ThemeDocumentDataDefaultItem {
  /**
   * text color field in *theme → default*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.default[].text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * background color field in *theme → default*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.default[].background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Item in *theme → characters*
 */
export interface ThemeDocumentDataCharactersItem {
  /**
   * text color field in *theme → characters*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.characters[].text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * background color field in *theme → characters*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.characters[].background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Item in *theme → about*
 */
export interface ThemeDocumentDataAboutItem {
  /**
   * text color field in *theme → about*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.about[].text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * background color field in *theme → about*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.about[].background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Item in *theme → episodes*
 */
export interface ThemeDocumentDataEpisodesItem {
  /**
   * text color field in *theme → episodes*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.episodes[].text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * background color field in *theme → episodes*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.episodes[].background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Item in *theme → episode card*
 */
export interface ThemeDocumentDataEpisodeCardItem {
  /**
   * text color field in *theme → episode card*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.episode_card[].text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * background color field in *theme → episode card*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.episode_card[].background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Content for theme documents
 */
interface ThemeDocumentData {
  /**
   * default field in *theme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.default[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  default: prismic.GroupField<Simplify<ThemeDocumentDataDefaultItem>>;

  /**
   * characters field in *theme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.characters[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  characters: prismic.GroupField<Simplify<ThemeDocumentDataCharactersItem>>;

  /**
   * about field in *theme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.about[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  about: prismic.GroupField<Simplify<ThemeDocumentDataAboutItem>>;

  /**
   * episodes field in *theme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.episodes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  episodes: prismic.GroupField<Simplify<ThemeDocumentDataEpisodesItem>>;

  /**
   * episode card field in *theme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: theme.episode_card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  episode_card: prismic.GroupField<Simplify<ThemeDocumentDataEpisodeCardItem>>;
}

/**
 * theme document from Prismic
 *
 * - **API ID**: `theme`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThemeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ThemeDocumentData>, "theme", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | CollapsibleCollectionDocument
  | EpisodeDocument
  | EpisodesDocument
  | HomeDocument
  | NavDocument
  | ThemeDocument;

/**
 * Primary content in *Chapter → Primary*
 */
export interface ChapterSliceDefaultPrimary {
  /**
   * Title field in *Chapter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Chapter → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Chapter → Items*
 */
export interface ChapterSliceDefaultItem {
  /**
   * episode field in *Chapter → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.items[].episode
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  episode: prismic.ContentRelationshipField<"episode">;
}

/**
 * Default variation for Chapter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChapterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChapterSliceDefaultPrimary>,
  Simplify<ChapterSliceDefaultItem>
>;

/**
 * Slice variation for *Chapter*
 */
type ChapterSliceVariation = ChapterSliceDefault;

/**
 * Chapter Shared Slice
 *
 * - **API ID**: `chapter`
 * - **Description**: Chapter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChapterSlice = prismic.SharedSlice<
  "chapter",
  ChapterSliceVariation
>;

/**
 * Default variation for CollapsibleCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapsibleCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CollapsibleCollection*
 */
type CollapsibleCollectionSliceVariation = CollapsibleCollectionSliceDefault;

/**
 * CollapsibleCollection Shared Slice
 *
 * - **API ID**: `collapsible_collection`
 * - **Description**: CollapsibleCollection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapsibleCollectionSlice = prismic.SharedSlice<
  "collapsible_collection",
  CollapsibleCollectionSliceVariation
>;

/**
 * Primary content in *LinkWithImage → Primary*
 */
export interface LinkWithImageSliceDefaultPrimary {
  /**
   * link field in *LinkWithImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_with_image.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * image field in *LinkWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *LinkWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_with_image.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for LinkWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkWithImage*
 */
type LinkWithImageSliceVariation = LinkWithImageSliceDefault;

/**
 * LinkWithImage Shared Slice
 *
 * - **API ID**: `link_with_image`
 * - **Description**: LinkWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkWithImageSlice = prismic.SharedSlice<
  "link_with_image",
  LinkWithImageSliceVariation
>;

/**
 * Primary content in *NavLinks → Primary*
 */
export interface NavLinksSliceDefaultPrimary {
  /**
   * link field in *NavLinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_links.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * text field in *NavLinks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_links.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for NavLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavLinksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavLinks*
 */
type NavLinksSliceVariation = NavLinksSliceDefault;

/**
 * NavLinks Shared Slice
 *
 * - **API ID**: `nav_links`
 * - **Description**: NavLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavLinksSlice = prismic.SharedSlice<
  "nav_links",
  NavLinksSliceVariation
>;

/**
 * Primary content in *ThemeItem → Primary*
 */
export interface ThemeItemSliceDefaultPrimary {
  /**
   * item name field in *ThemeItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_item.primary.item_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_name: prismic.KeyTextField;

  /**
   * text color field in *ThemeItem → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_item.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * background color field in *ThemeItem → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: theme_item.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for ThemeItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThemeItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThemeItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThemeItem*
 */
type ThemeItemSliceVariation = ThemeItemSliceDefault;

/**
 * ThemeItem Shared Slice
 *
 * - **API ID**: `theme_item`
 * - **Description**: ThemeItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThemeItemSlice = prismic.SharedSlice<
  "theme_item",
  ThemeItemSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      CollapsibleCollectionDocument,
      CollapsibleCollectionDocumentData,
      EpisodeDocument,
      EpisodeDocumentData,
      EpisodesDocument,
      EpisodesDocumentData,
      HomeDocument,
      HomeDocumentData,
      NavDocument,
      NavDocumentData,
      ThemeDocument,
      ThemeDocumentData,
      AllDocumentTypes,
      ChapterSlice,
      ChapterSliceVariation,
      ChapterSliceDefault,
      CollapsibleCollectionSlice,
      CollapsibleCollectionSliceVariation,
      CollapsibleCollectionSliceDefault,
      LinkWithImageSlice,
      LinkWithImageSliceVariation,
      LinkWithImageSliceDefault,
      NavLinksSlice,
      NavLinksSliceVariation,
      NavLinksSliceDefault,
      ThemeItemSlice,
      ThemeItemSliceVariation,
      ThemeItemSliceDefault,
    };
  }
}
